# Generated by Django 5.1.6 on 2025-02-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Контент")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog/image", verbose_name="Изображение"),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                ("is_publication", models.BooleanField(default=False, verbose_name="Признак публикации")),
                ("views", models.IntegerField(default=0, verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
                "ordering": ["-is_publication", "-created_at"],
            },
        ),
    ]
