# Generated by Django 5.1.6 on 2025-02-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]
