# Generated by Django 5.1.5 on 2025-02-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_contact_message_alter_contact_phone_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Контакт магазина", "verbose_name_plural": "Контакты магазина"},
        ),
        migrations.RemoveField(
            model_name="contact",
            name="message",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="name",
        ),
        migrations.AddField(
            model_name="contact",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Электронная почта"),
        ),
    ]
