# Generated by Django 5.1.5 on 2025-02-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_contact_options_remove_contact_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Платная категория"),
        ),
    ]
