# Generated by Django 5.1.6 on 2025-03-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_category_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_publication",
            field=models.BooleanField(default=False, verbose_name="Статус публикации"),
        ),
    ]
